input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000 
    codec => json
  }
}

filter {

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch-hot:9200"]
    index => "logstash-%{[@metadata][version]}-%{+YYYY.MM.dd}" 
  }
  stdout {
    codec => rubydebug
  }
}